version: '3.8'

services:
  airflow-init:
    build: .
    container_name: airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ../../dags:/opt/airflow/dags
      - ../../src:/opt/airflow/src
      - ../../data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow_db:/opt/airflow
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username ramon --password admin123 --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    restart: "no"

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ../../dags:/opt/airflow/dags
      - ../../src:/opt/airflow/src
      - ../../data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow_db:/opt/airflow
    ports:
      - "8080:8080"
    working_dir: /opt/airflow
    entrypoint: airflow webserver

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ../../dags:/opt/airflow/dags
      - ../../src:/opt/airflow/src
      - ../../data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow_db:/opt/airflow
    working_dir: /opt/airflow
    command: airflow scheduler
